/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sonerik.neuralnetworksandroid.ndk;

public class Callback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Callback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Callback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        neural_networkJNI.delete_Callback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    neural_networkJNI.Callback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    neural_networkJNI.Callback_change_ownership(this, swigCPtr, true);
  }

  public void epochPassed(int epoch, double recentAverageError) {
    if (getClass() == Callback.class) neural_networkJNI.Callback_epochPassed(swigCPtr, this, epoch, recentAverageError); else neural_networkJNI.Callback_epochPassedSwigExplicitCallback(swigCPtr, this, epoch, recentAverageError);
  }

  public Callback() {
    this(neural_networkJNI.new_Callback(), true);
    neural_networkJNI.Callback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
