/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sonerik.neuralnetworksandroid.ndk;

public class LearningResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LearningResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LearningResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        neural_networkJNI.delete_LearningResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTrainingSetOutputs(VectorOfVectorOfDouble value) {
    neural_networkJNI.LearningResult_trainingSetOutputs_set(swigCPtr, this, VectorOfVectorOfDouble.getCPtr(value), value);
  }

  public VectorOfVectorOfDouble getTrainingSetOutputs() {
    long cPtr = neural_networkJNI.LearningResult_trainingSetOutputs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorOfVectorOfDouble(cPtr, false);
  }

  public void setEpochsPassed(int value) {
    neural_networkJNI.LearningResult_epochsPassed_set(swigCPtr, this, value);
  }

  public int getEpochsPassed() {
    return neural_networkJNI.LearningResult_epochsPassed_get(swigCPtr, this);
  }

  public void setAverageError(double value) {
    neural_networkJNI.LearningResult_averageError_set(swigCPtr, this, value);
  }

  public double getAverageError() {
    return neural_networkJNI.LearningResult_averageError_get(swigCPtr, this);
  }

  public LearningResult() {
    this(neural_networkJNI.new_LearningResult(), true);
  }

}
