/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sonerik.neuralnetworksandroid.ndk;

public class VectorOfUnsigned {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfUnsigned(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfUnsigned obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        neural_networkJNI.delete_VectorOfUnsigned(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfUnsigned() {
    this(neural_networkJNI.new_VectorOfUnsigned__SWIG_0(), true);
  }

  public VectorOfUnsigned(long n) {
    this(neural_networkJNI.new_VectorOfUnsigned__SWIG_1(n), true);
  }

  public long size() {
    return neural_networkJNI.VectorOfUnsigned_size(swigCPtr, this);
  }

  public long capacity() {
    return neural_networkJNI.VectorOfUnsigned_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    neural_networkJNI.VectorOfUnsigned_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return neural_networkJNI.VectorOfUnsigned_isEmpty(swigCPtr, this);
  }

  public void clear() {
    neural_networkJNI.VectorOfUnsigned_clear(swigCPtr, this);
  }

  public void add(long x) {
    neural_networkJNI.VectorOfUnsigned_add(swigCPtr, this, x);
  }

  public long get(int i) {
    return neural_networkJNI.VectorOfUnsigned_get(swigCPtr, this, i);
  }

  public void set(int i, long val) {
    neural_networkJNI.VectorOfUnsigned_set(swigCPtr, this, i, val);
  }

}
