/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sonerik.neuralnetworksandroid.ndk;

public class VectorOfDouble {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        neural_networkJNI.delete_VectorOfDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfDouble() {
    this(neural_networkJNI.new_VectorOfDouble__SWIG_0(), true);
  }

  public VectorOfDouble(long n) {
    this(neural_networkJNI.new_VectorOfDouble__SWIG_1(n), true);
  }

  public long size() {
    return neural_networkJNI.VectorOfDouble_size(swigCPtr, this);
  }

  public long capacity() {
    return neural_networkJNI.VectorOfDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    neural_networkJNI.VectorOfDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return neural_networkJNI.VectorOfDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    neural_networkJNI.VectorOfDouble_clear(swigCPtr, this);
  }

  public void add(double x) {
    neural_networkJNI.VectorOfDouble_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return neural_networkJNI.VectorOfDouble_get(swigCPtr, this, i);
  }

  public void set(int i, double val) {
    neural_networkJNI.VectorOfDouble_set(swigCPtr, this, i, val);
  }

}
